[workspace]
resolver = "3"
members = [
    "crates/tekstide",
    "crates/tekstide-core",
]

[workspace.package]
version         = "0.5.0"
edition         = "2024"
license             = "Apache-2.0"
authors             = ["nabbisen"]
repository          = "https://github.com/nabbisen/tekstide"
categories          = ["command-line-utilities", "development-tools"]
keywords            = ["workspace", "developer-tools", "ai", "cli"]

[workspace.dependencies]
tekstide-core               = { version = "0", path = "crates/tekstide-core" }

libc                        = "0.2"

serde                       = { version = "1", features = ["derive"] }
serde_json                  = "1"
uuid                        = { version = "1", features = ["v4"] }
rusqlite                    = { version = "0.39", default-features = false, features = ["bundled"] }

iced                        = { version = "0.14", features = ["tokio", "advanced"] }
alacritty_terminal          = "0.26"
vte                         = "0.15"

fluent-bundle               = "0.16"
unic-langid                 = "0.9"
sys-locale                  = "0.3"
