//! RFC-056 PR-056-D: the AgentRun report, **assembled on demand and never
//! stored** (D5).
//!
//! Tekstide keeps exactly one copy of a run's facts — its record — so a purge
//! has exactly one thing to remove. A report is a pure function of that
//! record plus whatever transcript and change sets still exist, and the file
//! it is written to is the user's, outside the product's reach.
//!
//! **The report keeps three kinds of text apart, in the file and not only on
//! screen** (risk §3), because a handoff note exists so a reader knows which
//! sentences a person stands behind:
//!
//! | Section | Whose words | Marked |
//! | --- | --- | --- |
//! | *Written by you* | the user's classification and notes | every line begins `\| ` |
//! | *Recorded by Tekstide* | facts Tekstide holds | plain `Name: value` lines |
//! | *Derived from the run* | changed paths and transcript text, which an agent produced or touched | every line begins `> ` |
//!
//! Every untrusted value — the profile, the prompt summary, a custom label, a
//! path, a transcript line, and each line of the notes — goes through
//! [`quote_untrusted`]: control characters, bidi controls and newlines are
//! escaped, so **no value can add a line of its own, or end another section's
//! marker**. A note line the user typed as `> looks like agent output` is
//! written `| > looks like agent output`: the marker is applied *after* the
//! text, so the text cannot supply it.
//!
//! Nothing here reads a file, writes a file, or knows a path except
//! [`write_run_report`], the one place a report leaves the product.

use std::fs::OpenOptions;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

use crate::domain::{
    AgentRun, AgentRunOrigin, AgentRunStatus, DomainTimestamp, RunClassification, RunEnding,
};
use crate::text_safety::quote_untrusted;

/// How much of a transcript's tail a report quotes. The transcript is the only
/// place run content lives; a report quotes a bounded tail of it, and says how
/// much it left out.
pub const REPORT_TRANSCRIPT_TAIL_BYTES: usize = 16 * 1024;
/// How many changed paths a report lists. A run can change more; the report
/// says how many it left out.
pub const REPORT_MAX_CHANGED_PATHS: usize = 500;

/// The tail of a run's transcript, and how long the whole was.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TranscriptExcerpt<'a> {
    pub tail: &'a [u8],
    pub total_len: u64,
}

/// Everything a report is made of. **All borrowed**: the report owns nothing
/// the record does not, which is what "no second copy" means in the types.
#[derive(Clone, Copy, Debug)]
pub struct RunReportSources<'a> {
    pub run: &'a AgentRun,
    /// Project-relative paths of the changes attributed to this run.
    pub changed_paths: &'a [PathBuf],
    /// Paths that changed and are not in `changed_paths`.
    pub changed_paths_omitted: u64,
    pub transcript: Option<TranscriptExcerpt<'a>>,
    pub generated_at: &'a DomainTimestamp,
}

/// What a report will contain, for the export prompt to say **before** the
/// file is written (D5).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RunReportContents {
    pub has_classification: bool,
    pub has_notes: bool,
    pub changed_paths: usize,
    pub transcript_bytes_quoted: usize,
}

pub fn run_report_contents(sources: &RunReportSources<'_>) -> RunReportContents {
    RunReportContents {
        has_classification: sources.run.classification.is_some(),
        has_notes: sources.run.notes().is_some(),
        changed_paths: sources.changed_paths.len().min(REPORT_MAX_CHANGED_PATHS),
        transcript_bytes_quoted: sources.transcript.map_or(0, |excerpt| {
            excerpt.tail.len().min(REPORT_TRANSCRIPT_TAIL_BYTES)
        }),
    }
}

/// Marks a line as the user's own words.
const USER_MARK: &str = "| ";
/// Marks a line as derived from the run: an agent produced or touched it.
const RUN_MARK: &str = "> ";

pub fn render_run_report(sources: &RunReportSources<'_>) -> String {
    let run = sources.run;
    let mut out = String::new();
    let mut line = |text: &str| {
        out.push_str(text);
        out.push('\n');
    };

    line("# AgentRun report");
    line("");
    line(&format!(
        "Generated by Tekstide at {} from this run's record and what was still on disk.",
        sources.generated_at.as_str()
    ));
    line("Tekstide keeps no copy of this file and cannot change or remove it.");
    line("");
    line(
        "Three kinds of text are kept apart below. Lines beginning `| ` are the user's own words.",
    );
    line("Lines beginning `> ` were produced or touched by the run, not written by a person.");
    line("Lines beginning with neither are facts Tekstide recorded.");
    line("");

    line("## Written by you");
    line("");
    match &run.classification {
        Some(classification) => {
            line(&format!(
                "{USER_MARK}Classification: {}",
                classification_text(classification)
            ));
        }
        None => line(&format!("{USER_MARK}Classification: none")),
    }
    match run.notes() {
        Some(notes) => {
            line(&format!("{USER_MARK}Notes:"));
            for note_line in notes.lines() {
                line(&format!(
                    "{USER_MARK}{}",
                    quote_untrusted(note_line).as_str()
                ));
            }
        }
        None => line(&format!("{USER_MARK}Notes: none")),
    }
    line("");

    line("## Recorded by Tekstide");
    line("");
    line(&format!("Run: {}", run.id.as_str()));
    line(&format!(
        "Profile: {}",
        quote_untrusted(&run.profile_id).as_str()
    ));
    line(&format!(
        "Prompt summary: {}",
        quote_untrusted(&run.prompt_summary).as_str()
    ));
    line(&format!(
        "Started: {}",
        run.started_at
            .as_ref()
            .map_or("not recorded", DomainTimestamp::as_str)
    ));
    line(&format!("Ended: {}", ending_text(run)));
    line(&format!("Status when last recorded: {}", status_text(run)));
    line(&format!(
        "Approvals: {}. Change sets: {}. Audit events: {}.",
        count_text(
            run.approval_ids.len(),
            run.record_bounds.omitted_approval_ids
        ),
        count_text(
            run.change_set_ids.len(),
            run.record_bounds.omitted_change_set_ids
        ),
        count_text(
            run.audit_event_ids.len(),
            run.record_bounds.omitted_audit_event_ids
        ),
    ));
    for omission in bounded_notes(run) {
        line(&format!("Left out of the record: {omission}"));
    }
    line("");

    line("## Derived from the run");
    line("");
    line("Changed files attributed to this run (paths inside the project):");
    if sources.changed_paths.is_empty() {
        line("(none recorded)");
    }
    for path in sources.changed_paths.iter().take(REPORT_MAX_CHANGED_PATHS) {
        line(&format!(
            "{RUN_MARK}{}",
            quote_untrusted(&path.to_string_lossy()).as_str()
        ));
    }
    let omitted = sources.changed_paths_omitted.saturating_add(
        sources
            .changed_paths
            .len()
            .saturating_sub(REPORT_MAX_CHANGED_PATHS) as u64,
    );
    if omitted > 0 {
        line(&format!("{omitted} more changed paths are not listed."));
    }
    line("");
    match sources.transcript {
        Some(excerpt) => {
            let tail = &excerpt.tail[excerpt
                .tail
                .len()
                .saturating_sub(REPORT_TRANSCRIPT_TAIL_BYTES)..];
            line(&format!(
                "Transcript: the last {} bytes of {}, quoted:",
                tail.len(),
                excerpt.total_len
            ));
            let text = String::from_utf8_lossy(tail);
            for transcript_line in text.split('\n') {
                let transcript_line = transcript_line
                    .strip_suffix('\r')
                    .unwrap_or(transcript_line);
                line(&format!(
                    "{RUN_MARK}{}",
                    quote_untrusted(transcript_line).as_str()
                ));
            }
        }
        None => line("Transcript: none is available."),
    }
    out
}

fn classification_text(classification: &RunClassification) -> String {
    match classification {
        RunClassification::Coding => "coding".to_owned(),
        RunClassification::Review => "review".to_owned(),
        RunClassification::Documentation => "documentation".to_owned(),
        RunClassification::Testing => "testing".to_owned(),
        RunClassification::Refactoring => "refactoring".to_owned(),
        RunClassification::Release => "release".to_owned(),
        RunClassification::Custom(label) => format!("custom: {}", quote_untrusted(label).as_str()),
    }
}

/// **Unknown is unknown** (D12): a restored run whose ending was not seen says
/// so, and never a time it was not.
fn ending_text(run: &AgentRun) -> String {
    match &run.ending {
        RunEnding::Ended(at) => at.as_str().to_owned(),
        RunEnding::NotEnded => "not ended when this record was written".to_owned(),
        RunEnding::Unknown => "unknown: Tekstide did not see this run end".to_owned(),
    }
}

fn status_text(run: &AgentRun) -> &'static str {
    let restored = run.origin == AgentRunOrigin::RestoredFromRecord;
    match (run.status, restored) {
        (AgentRunStatus::Detached, true) => "unknown (restored from its record)",
        (AgentRunStatus::Draft, _) => "draft",
        (AgentRunStatus::Ready, _) => "ready",
        (AgentRunStatus::Preparing, _) => "preparing",
        (AgentRunStatus::Running, _) => "running",
        (AgentRunStatus::AwaitingApproval, _) => "awaiting approval",
        (AgentRunStatus::ReviewReady, _) => "review ready",
        (AgentRunStatus::Completed, _) => "completed",
        (AgentRunStatus::Failed, _) => "failed",
        (AgentRunStatus::Cancelled, _) => "cancelled",
        (AgentRunStatus::Detached, false) => "detached",
    }
}

fn count_text(kept: usize, omitted: u64) -> String {
    if omitted == 0 {
        kept.to_string()
    } else {
        format!("{kept} listed, {omitted} more not recorded")
    }
}

/// What the record was bounded on, so a bounded record says so in the report.
fn bounded_notes(run: &AgentRun) -> Vec<&'static str> {
    let bounds = &run.record_bounds;
    let mut notes = Vec::new();
    if bounds.notes_truncated {
        notes.push("the end of the notes");
    }
    if bounds.classification_label_truncated {
        notes.push("the end of the custom classification");
    }
    if bounds.prompt_summary_truncated {
        notes.push("the end of the prompt summary");
    }
    notes
}

/// Why a report was not written. **Nothing is written on any of them.**
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReportExportRefusal {
    /// A relative path would be written wherever the process happens to be.
    NotAbsolute,
    /// The folder to write into does not exist.
    FolderMissing,
    /// **A report never overwrites**: the user's file, or the user's other
    /// report, is not Tekstide's to replace.
    AlreadyExists,
    /// The state directory is Tekstide's, and a report is the user's file.
    InsideStateDirectory,
    /// The operating system refused the write.
    WriteFailed,
}

/// The one place a report leaves the product (D5): a new file at a path the
/// user gave, **never overwriting**, readable by its owner only, because it
/// names project paths and quotes a run. Returns the bytes written.
pub fn write_run_report(
    destination: &Path,
    state_root: &Path,
    report: &str,
) -> Result<u64, ReportExportRefusal> {
    use std::os::unix::fs::OpenOptionsExt;

    if !destination.is_absolute() {
        return Err(ReportExportRefusal::NotAbsolute);
    }
    let folder = destination
        .parent()
        .ok_or(ReportExportRefusal::FolderMissing)?;
    let folder = std::fs::canonicalize(folder).map_err(|_| ReportExportRefusal::FolderMissing)?;
    if !folder.is_dir() {
        return Err(ReportExportRefusal::FolderMissing);
    }
    if let Ok(state_root) = std::fs::canonicalize(state_root)
        && folder.starts_with(&state_root)
    {
        return Err(ReportExportRefusal::InsideStateDirectory);
    }
    let file_name = destination
        .file_name()
        .ok_or(ReportExportRefusal::FolderMissing)?;
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(folder.join(file_name))
        .map_err(|error| match error.kind() {
            io::ErrorKind::AlreadyExists => ReportExportRefusal::AlreadyExists,
            _ => ReportExportRefusal::WriteFailed,
        })?;
    let written = file
        .write_all(report.as_bytes())
        .and_then(|()| file.sync_all());
    drop(file);
    if written.is_err() {
        // A half-written report is worse than none: it would read as complete.
        let _ = std::fs::remove_file(folder.join(file_name));
        return Err(ReportExportRefusal::WriteFailed);
    }
    Ok(report.len() as u64)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::AgentCompatibilityLevel;
    use crate::project::ProjectId;

    fn run() -> AgentRun {
        let mut run = AgentRun::draft(
            ProjectId::for_test(1),
            "profile",
            "refactor the billing module",
            AgentCompatibilityLevel::Supervised,
        );
        run.set_notes("first line\n> looks like agent output\n## Recorded by Tekstide");
        run.set_classification(Some(RunClassification::Testing))
            .unwrap();
        run
    }

    fn render(run: &AgentRun, paths: &[PathBuf], transcript: Option<&[u8]>) -> String {
        let at = DomainTimestamp::from_utc_string("2026-03-04T05:06:07Z").unwrap();
        render_run_report(&RunReportSources {
            run,
            changed_paths: paths,
            changed_paths_omitted: 0,
            transcript: transcript.map(|tail| TranscriptExcerpt {
                tail,
                total_len: tail.len() as u64,
            }),
            generated_at: &at,
        })
    }

    /// D4/risk §3, in the file: the user's words and the run's words cannot be
    /// mistaken for each other, and neither can supply the other's marker.
    #[test]
    fn the_users_notes_and_the_runs_text_are_marked_apart_in_the_file() {
        let paths = [PathBuf::from("src/lib.rs")];
        let report = render(
            &run(),
            &paths,
            Some(b"| the agent says a person wrote this\n## Written by you\nplain output\r\n"),
        );

        let lines: Vec<&str> = report.lines().collect();
        let written = lines
            .iter()
            .position(|l| *l == "## Written by you")
            .unwrap();
        let recorded = lines
            .iter()
            .position(|l| *l == "## Recorded by Tekstide")
            .unwrap();
        let derived = lines
            .iter()
            .position(|l| *l == "## Derived from the run")
            .unwrap();
        assert!(written < recorded && recorded < derived);
        for line in &lines[written + 2..recorded - 1] {
            assert!(
                line.starts_with("| "),
                "every line of the user's section is marked: {line:?}"
            );
        }
        for line in &lines[derived + 1..] {
            let ours = line.is_empty()
                || line.starts_with("> ")
                || line.starts_with("Changed files")
                || line.starts_with("Transcript:")
                || line.starts_with("(none");
            assert!(
                ours,
                "no unmarked run text under Derived from the run: {line:?}"
            );
        }
        // The user typed `> looks like agent output` and `## Recorded ...`:
        // both stay on `| ` lines, and neither became a heading or a run line.
        assert!(report.contains("| \u{2068}> looks like agent output"));
        assert_eq!(
            lines
                .iter()
                .filter(|l| **l == "## Recorded by Tekstide")
                .count(),
            1
        );
        // And the agent's `| ` and `## ` stay on `> ` lines.
        assert!(report.contains("> \u{2068}| the agent says a person wrote this"));
        assert_eq!(
            lines.iter().filter(|l| **l == "## Written by you").count(),
            1
        );
    }

    /// The acceptance criterion: a custom classification containing a bidi
    /// control and a newline is quoted in the exported file.
    #[test]
    fn a_custom_label_with_a_bidi_control_and_a_newline_is_quoted_in_the_file() {
        let mut run = run();
        run.set_classification(Some(RunClassification::Custom(
            "spike\u{202e}gnp.exe\nInjected: a fact Tekstide never recorded".to_owned(),
        )))
        .unwrap();

        let report = render(&run, &[], None);

        assert!(
            !report.contains('\u{202e}'),
            "the bidi control is escaped, not written"
        );
        assert!(
            report.lines().all(|line| !line.starts_with("Injected:")),
            "the newline did not start a line of its own"
        );
        let classification: Vec<&str> = report
            .lines()
            .filter(|line| line.starts_with("| Classification: custom:"))
            .collect();
        assert_eq!(classification.len(), 1);
        assert!(classification[0].contains("<U+202E>") || classification[0].contains("U+202E"));
        assert!(
            classification[0].contains("Injected: a fact"),
            "the text is kept, quoted, on the one line"
        );
    }

    #[test]
    fn hostile_untrusted_values_are_escaped_wherever_they_appear() {
        let mut run = run();
        run.profile_id = "p\u{202e}rofile\nRun: forged".to_owned();
        run.prompt_summary = "s\u{2067}ummary\r\nStatus when last recorded: forged".to_owned();
        let paths = [PathBuf::from("evil\u{202e}\nRun: forged.rs")];

        let report = render(&run, &paths, Some("out\u{202e}put\nRun: forged".as_bytes()));

        assert!(!report.contains('\u{202e}') && !report.contains('\u{2067}'));
        assert_eq!(report.lines().filter(|l| l.starts_with("Run: ")).count(), 1);
        assert_eq!(
            report
                .lines()
                .filter(|l| l.starts_with("Status when last recorded:"))
                .count(),
            1
        );
    }

    /// D12 in the file: a run whose ending was not seen does not get one.
    #[test]
    fn a_run_whose_ending_was_not_seen_says_so_in_the_file() {
        let mut run = run();
        run.origin = AgentRunOrigin::RestoredFromRecord;
        run.status = AgentRunStatus::Detached;
        run.ending = RunEnding::Unknown;
        run.started_at = Some(DomainTimestamp::from_utc_string("2026-03-04T01:00:00Z").unwrap());

        let report = render(&run, &[], None);

        assert!(report.contains("Ended: unknown: Tekstide did not see this run end"));
        assert!(report.contains("Started: 2026-03-04T01:00:00Z"));
        assert!(
            !report.contains("2026-03-04T05:06:07Z\nEnded"),
            "not the time the report was made"
        );
        assert!(report.contains("Status when last recorded: unknown (restored from its record)"));
    }

    #[test]
    fn a_bounded_record_says_so_in_the_report() {
        let mut run = run();
        run.record_bounds.omitted_approval_ids = 7;
        run.record_bounds.notes_truncated = true;

        let report = render(&run, &[], None);

        assert!(report.contains("0 listed, 7 more not recorded"));
        assert!(report.contains("Left out of the record: the end of the notes"));
    }

    #[test]
    fn the_report_says_what_it_will_contain_before_it_is_written() {
        let paths = [PathBuf::from("a.rs"), PathBuf::from("b.rs")];
        let run = run();
        let at = DomainTimestamp::now_utc();
        let contents = run_report_contents(&RunReportSources {
            run: &run,
            changed_paths: &paths,
            changed_paths_omitted: 0,
            transcript: Some(TranscriptExcerpt {
                tail: &[b'x'; 100],
                total_len: 100,
            }),
            generated_at: &at,
        });

        assert_eq!(
            contents,
            RunReportContents {
                has_classification: true,
                has_notes: true,
                changed_paths: 2,
                transcript_bytes_quoted: 100,
            }
        );
    }

    #[test]
    fn the_transcript_tail_is_bounded_and_the_report_says_how_long_the_whole_was() {
        let big = vec![b'z'; REPORT_TRANSCRIPT_TAIL_BYTES * 3];
        let at = DomainTimestamp::now_utc();
        let run = run();
        let report = render_run_report(&RunReportSources {
            run: &run,
            changed_paths: &[],
            changed_paths_omitted: 0,
            transcript: Some(TranscriptExcerpt {
                tail: &big,
                total_len: 5_000_000,
            }),
            generated_at: &at,
        });

        assert!(report.contains(&format!(
            "the last {REPORT_TRANSCRIPT_TAIL_BYTES} bytes of 5000000"
        )));
        assert!(report.len() < REPORT_TRANSCRIPT_TAIL_BYTES * 2);
    }

    #[test]
    fn a_report_is_written_as_a_new_private_file_and_never_overwrites() {
        use std::os::unix::fs::PermissionsExt;
        let base = std::env::temp_dir().join(format!("tekstide-report-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let state = base.join("state");
        let out = base.join("out");
        std::fs::create_dir_all(&state).unwrap();
        std::fs::create_dir_all(&out).unwrap();
        let target = out.join("report.md");

        let written = write_run_report(&target, &state, "the report\n").unwrap();
        assert_eq!(written, 11);
        assert_eq!(std::fs::read_to_string(&target).unwrap(), "the report\n");
        assert_eq!(
            std::fs::metadata(&target).unwrap().permissions().mode() & 0o777,
            0o600
        );

        assert_eq!(
            write_run_report(&target, &state, "second"),
            Err(ReportExportRefusal::AlreadyExists)
        );
        assert_eq!(
            std::fs::read_to_string(&target).unwrap(),
            "the report\n",
            "untouched"
        );

        let victim = out.join("victim.txt");
        std::fs::write(&victim, "the user's file").unwrap();
        std::os::unix::fs::symlink(&victim, out.join("link.md")).unwrap();
        assert_eq!(
            write_run_report(&out.join("link.md"), &state, "x"),
            Err(ReportExportRefusal::AlreadyExists),
            "not written through a symlink"
        );
        assert_eq!(std::fs::read_to_string(&victim).unwrap(), "the user's file");

        assert_eq!(
            write_run_report(Path::new("relative.md"), &state, "x"),
            Err(ReportExportRefusal::NotAbsolute)
        );
        assert_eq!(
            write_run_report(&base.join("no-such-folder/report.md"), &state, "x"),
            Err(ReportExportRefusal::FolderMissing)
        );
        assert_eq!(
            write_run_report(&state.join("report.md"), &state, "x"),
            Err(ReportExportRefusal::InsideStateDirectory)
        );
        assert!(!state.join("report.md").exists());
        let _ = std::fs::remove_dir_all(&base);
    }
}
